apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jao080lqy-python 
  janus-idp.io/tekton: jao080lqy-python
  backstage.io/kubernetes-id: jao080lqy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jao080lqy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml