apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jao080lqy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jao080lqy-python 
  name: jao080lqy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jao080lqy-python 
